### ISSUE TITLE
Enable Users to Define Initial Network Conditions (Including Packet Loss)

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/Congestion-Control-Simulator#1]
# 🐛Bug-Report

### Expected behavior
1. A form or input interface will allow users to set network conditions like packet loss rate, latency, and bandwidth.
2. Once the conditions are defined, the simulation will start with the provided parameters and run automatically.
3. The need for pressing buttons to manually simulate packet loss or latency during the simulation will be removed.

### Current behavior
Currently, users need to manually simulate network conditions by pressing buttons during the simulation. This feature request aims to allow users to define the network conditions (such as packet loss, latency, and bandwidth) at the start of the simulation. Users should be able to input these parameters before running the simulation, which will then automatically reflect in the simulation without manual intervention.

### Steps to reproduce

1. Run the simulator.
2. Start a simulation with default settings.
3. Manually click buttons to simulate packet loss, transfer, etc.

### Possible Solution
Add an interface (either in the form of input fields or a configuration file) that accepts initial values for network parameters. The simulator will use these inputs to initialize and run the simulation based on the defined network conditions.

### Context (Your working environment)
Browser: [e.g., Chrome, Firefox]
Operating System: [e.g., Windows, macOS, Linux]

### Detailed Description (screenshots, code snippets etc.)
1. Include screenshots of the current simulation setup interface.
2. Code snippets of where the manual button presses are handled might help in understanding where to implement the initial condition setup.

**Comment by haseeb-555** [comment]
hey, can i get the access to sort out this issue

**Comment by haseeb-555** [comment]
Thanks for assigning the issue , i am working on it
