### ISSUE TITLE
Improve Visualization of Network Traffic

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/Congestion-Control-Simulator#2]
#  🚀Feature Request

### Description
Currently, the simulator lacks a detailed and dynamic visual representation of network traffic during simulations. Improving the visualization will allow users to better understand key parameters like throughput, packet loss, latency, and congestion in real-time. This feature will enhance the user experience by providing visual insights into how different congestion control algorithms perform under varying network conditions.

### Why is this feature important to you?
For real-time network visualization

### Describe the solution you'd like
A real-time graphical interface displaying network metrics such as:

1. Throughput (bandwidth usage over time)
2. Packet loss (packets lost over time)
3. Latency (delay variations over time)
4. Congestion window size (if applicable to the algorithm)

The graphs should update dynamically as the simulation progresses.
Users should be able to view all key metrics on a single dashboard, and the graphs should scale based on the simulation duration.

Possible Solution:

1. Integrate a graphing library like Chart.js or D3.js to generate real-time plots of network metrics.
2. Create a dashboard that displays these graphs and updates them as the simulation progresses.
3. Use event listeners or hooks in the simulator code to feed data into the visualization component in real-time.

**Comment by shikharpandya0487** [comment]
Thank you for assigning the issue mam I have started to work on it.

**Comment by shikharpandya0487** [comment]
Mam could I add a navbar and under that the dashboard will have the above features 
I went through other issues in the project and thought it will be easier for others as well to add if a navbar is there.

**Comment by Nandika-A** [comment]
> Mam could I add a navbar and under that the dashboard will have the above features I went through other issues in the project and thought it will be easier for others as well to add if a navbar is there.

Yes that will be nice.

**Comment by shikharpandya0487** [comment]
Good evening mam 
Mam I have made the features half way only but unfortunately there are relatives visit at home so I would be able to continue once I return to clg on 14th . If till then no successful PR has merged could I get a second chance ?

**Comment by aachintya** [comment]
I made a request on contrihub website. I am willing to try

**Comment by Nandika-A** [comment]
> Good evening mam Mam I have made the features half way only but unfortunately there are relatives visit at home so I would be able to continue once I return to clg on 14th . If till then no successful PR has merged could I get a second chance ?

Yes sure, if this issue isn't completed.

**Comment by Nandika-A** [comment]
> I made a request on contrihub website. I am willing to try

You haven't made request for this issue on the site, it's another one.

**Comment by aachintya** [comment]
ok mam requested now
