### ISSUE TITLE
Add Logging for Simulation Results

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/Congestion-Control-Simulator#3]
# 🚀Feature Request

### **Description**  
*Please describe the problem you are trying to solve.*  
Currently, the simulator does not provide any functionality to save or log the simulation results for further analysis. Users must manually monitor the output during the simulation, making it difficult to retain data for review or comparisons after the simulation has ended.

---

### **Why is this feature important to you?**  
*Is your feature request related to a problem? Please describe.*  
Logging simulation results is crucial for users who want to analyze performance metrics like throughput, latency, and packet loss after the simulation. It is especially useful for comparing different congestion control algorithms or for debugging purposes. Without logging, users have no way to retain detailed results for future reference or deeper analysis.

---

### **Describe the solution you'd like**  
*Please describe the desired behavior.*  
- Implement a logging mechanism that automatically saves key simulation metrics (e.g., throughput, packet loss, latency, congestion window size) to a file.
- Users should be able to choose the output format (e.g., `.csv`, `.json`).
- The log file should include:
  - Timestamps
  - Algorithm used
  - Configured network conditions (e.g., packet loss rate, latency)
  - Results of the simulation (e.g., packet loss percentage, average latency)
  
Example log file structure in **CSV** format:

```csv
Timestamp, Algorithm, Packet Loss (%), Average Latency (ms), Throughput (Mbps)
2024-10-07 10:23:45, TCP, 1.5, 50, 100
2024-10-07 10:24:10, Cubic, 2.0, 55, 95
```

---

### **Additional context**  
*Please describe alternative solutions or features you have considered.*  
- One alternative could be providing an option to export the results directly from the UI after the simulation, but automatic logging ensures that users don't miss important data.
- Another enhancement could be integrating a downloadable report feature summarizing the simulation with visual charts.

**Comment by haseeb-555** [comment]
Thanks for assigning the issue i am working on it

**Comment by aachintya** [comment]
i have started working as my request was accepted

**Comment by aachintya** [comment]
Hello mam , i can implement this but only after the auto simulation is implemented [which is a pending PR due to conflicts](https://github.com/ContriHUB/Congestion-Control-Simulator/pull/6), should i also implement auto simulation  ? or what should i do ?

**Comment by Nandika-A** [comment]
> Hello mam , i can implement this but only after the auto simulation is implemented [which is a pending PR due to conflicts](https://github.com/ContriHUB/Congestion-Control-Simulator/pull/6), should i also implement auto simulation ? or what should i do ?

Ya that's right, you can implement auto simulation as well then. Request it on contrihub's site once the server is up.

**Comment by aachintya** [comment]
> > Hello mam , i can implement this but only after the auto simulation is implemented [which is a pending PR due to conflicts](https://github.com/ContriHUB/Congestion-Control-Simulator/pull/6), should i also implement auto simulation ? or what should i do ?
> 
> Ya that's right, you can implement auto simulation as well then. Request it on contrihub's site once the server is up.

ok mam

**Comment by aachintya** [comment]
i had one doubt, should i simulate packet loss also automatically ?
In the current implementation, packet loss will only occur if we manually mark a packet as lost by using the "Mark as Lost" button. This means that during automatic simulation, if we don't interact with that button, packet loss will remain zero throughout the simulation.
so I was thinking of using probability to trigger packet-loss. I would use `Math.random()` to generate a number between 0 and 1.  If the generated number is less than packetLossRate, a packet loss event is triggered. 
What should i set the probability percentage. i was thinking 10% but that is too high for real life scenarios[ according to this](https://tomtalks.blog/what-are-thresholds-for-good-and-poor-network-packet-loss-jitter-and-round-trip-time-for-unified-communications/). Generally its 1-2% but that would lead us to run the simulator for a longer time (only 1 in 100 iterations a packet-loss would occur). So what should set it to ?

**Comment by Nandika-A** [comment]
> i had one doubt, should i simulate packet loss also automatically ? In the current implementation, packet loss will only occur if we manually mark a packet as lost by using the "Mark as Lost" button. This means that during automatic simulation, if we don't interact with that button, packet loss will remain zero throughout the simulation. so I was thinking of using probability to trigger packet-loss. I would use `Math.random()` to generate a number between 0 and 1. If the generated number is less than packetLossRate, a packet loss event is triggered. What should i set the probability percentage. i was thinking 10% but that is too high for real life scenarios[ according to this](https://tomtalks.blog/what-are-thresholds-for-good-and-poor-network-packet-loss-jitter-and-round-trip-time-for-unified-communications/). Generally its 1-2% but that would lead us to run the simulator for a longer time (only 1 in 100 iterations a packet-loss would occur). So what should set it to ?

Include both of these functionalities where the user can either enter the packet sequence numbers manually or some percentage of the packets transferred as simulated as lost. Manually entering the packet loss is also important for the learners. Also in the computer networks exam the lost packets' sequence numbers are provided, instead of the fraction of packets lost.

**Comment by aachintya** [comment]
> > i had one doubt, should i simulate packet loss also automatically ? In the current implementation, packet loss will only occur if we manually mark a packet as lost by using the "Mark as Lost" button. This means that during automatic simulation, if we don't interact with that button, packet loss will remain zero throughout the simulation. so I was thinking of using probability to trigger packet-loss. I would use `Math.random()` to generate a number between 0 and 1. If the generated number is less than packetLossRate, a packet loss event is triggered. What should i set the probability percentage. i was thinking 10% but that is too high for real life scenarios[ according to this](https://tomtalks.blog/what-are-thresholds-for-good-and-poor-network-packet-loss-jitter-and-round-trip-time-for-unified-communications/). Generally its 1-2% but that would lead us to run the simulator for a longer time (only 1 in 100 iterations a packet-loss would occur). So what should set it to ?
> 
> Include both of these functionalities where the user can either enter the packet sequence numbers manually or some percentage of the packets transferred as simulated as lost. Manually entering the packet loss is also important for the learners. Also in the computer networks exam the lost packets' sequence numbers are provided, instead of the fraction of packets lost.

Thank you mam. That's a very good solution
