### ISSUE TITLE
Implement support for additional congestion control algorithms in the simulator

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/Congestion-Control-Simulator#4]
#  🚀Feature Request

### Description
The simulator currently supports a limited set of congestion control algorithms. By implementing additional algorithms such as fast recovery and fast retransmit, the simulator would become more versatile and useful for testing and educational purposes.

### Why is this feature important to you?
Supporting a wider range of congestion control algorithms will make the simulator more comprehensive, allowing users to study and compare the behavior of different algorithms under various network conditions.

### Describe the solution you'd like
The simulator should allow users to easily switch between algorithms and simulate different scenarios. Additionally, ensure that these algorithms are integrated with the current simulation framework, and provide clear documentation on how to use them.

**Comment by aachintya** [comment]
is it liking combining Fast Retransmit and fast recovery ?

**Comment by Nandika-A** [comment]
> is it liking combining Fast Retransmit and fast recovery ?

Fast recovery is an extension of fast retransmit. First three duplicate packet transfer are handled by fast retransmit, and after that fast recovery is applicable. Indeed all these algorithms: slow start, congestion avoidance, fast retransmit and fast recovery are the extension of the previous in different network conditions.

**Comment by DeshDeepakKushwaha** [comment]
thanku for assigning this issue to me.working on it now!!

**Comment by Gprakhar141** [comment]
Thanks for assigning, starting on it...

**Comment by Gprakhar141** [comment]
@Nandika-A Mam I have raised a PR for this issue, please review it.
